/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tuninglogbook;

import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author mauri
 */
public class rowPanel extends javax.swing.JPanel {

    /**
     * Creates new form rowPanel
     */
    
    //Some variables to instantiate
    Log entry;
    
    public rowPanel() {
        initComponents();
        entry = new Log();
    }
    
    public Log getEntry(){ 
        String time = timeTF.getText();        
        entry.setTime(time);
        String name = nameTF.getText();        
        entry.setName(name); 
        String event = eventTF.getText();        
        entry.setEvent(event);
        String notes = notesTA.getText();
        entry.setNotes(notes);
        return entry;
    }            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLB = new javax.swing.JLabel();
        timeLB = new javax.swing.JLabel();
        eventLB = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        timeTF = new javax.swing.JTextField();
        eventTF = new javax.swing.JTextField();
        currTimeLB = new javax.swing.JLabel();
        currentTimeBtn = new javax.swing.JButton();
        notesLB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesTA = new javax.swing.JTextArea();
        setupLB = new javax.swing.JLabel();
        setupBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 300));

        nameLB.setText("Name");

        timeLB.setText("Time");

        eventLB.setText("Event");

        nameTF.setText("Enter Name");

        timeTF.setText("Enter Time");

        eventTF.setText("Enter Event");

        currTimeLB.setText("Get Current Time");

        currentTimeBtn.setText("Get Time");
        currentTimeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentTimeBtnActionPerformed(evt);
            }
        });

        notesLB.setText(" Notes");

        notesTA.setColumns(20);
        notesTA.setRows(5);
        notesTA.setText("Add Some Notes about the event\n");
        jScrollPane1.setViewportView(notesTA);

        setupLB.setText("Setup");

        setupBtn.setText("See Setup");
        setupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(nameLB)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(currentTimeBtn)
                        .addGap(50, 50, 50)
                        .addComponent(eventTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(timeLB)
                        .addGap(69, 69, 69)
                        .addComponent(currTimeLB)
                        .addGap(59, 59, 59)
                        .addComponent(eventLB)
                        .addGap(122, 122, 122)
                        .addComponent(notesLB)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setupBtn)
                    .addComponent(setupLB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLB)
                    .addComponent(eventLB)
                    .addComponent(timeLB)
                    .addComponent(currTimeLB)
                    .addComponent(notesLB)
                    .addComponent(setupLB))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eventTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(currentTimeBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setupBtn))
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void currentTimeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentTimeBtnActionPerformed
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
        String time = s.format(Calendar.getInstance().getTime());
        timeTF.setText(time);
        //entry.setTime(time);         
    }//GEN-LAST:event_currentTimeBtnActionPerformed

    private void setupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setupBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currTimeLB;
    private javax.swing.JButton currentTimeBtn;
    private javax.swing.JLabel eventLB;
    private javax.swing.JTextField eventTF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLB;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel notesLB;
    private javax.swing.JTextArea notesTA;
    private javax.swing.JButton setupBtn;
    private javax.swing.JLabel setupLB;
    private javax.swing.JLabel timeLB;
    private javax.swing.JTextField timeTF;
    // End of variables declaration//GEN-END:variables
}
